import { Types } from "mongoose";
import { env } from "../config/env";
import { Contract } from "../models/mongo/Contract";
import { ContractTemplate } from "../models/mongo/ContractTemplate";
import { Invoice } from "../models/mongo/Invoice";
import {
  dollarsToCents,
  nextInvoiceNumber,
} from "../services/invoice.service";
import { endOfDay, startOfDay } from "../utils/contractDates";

/**
 * Create open renewal invoices for contracts due within the lead window.
 * Idempotent: skips contracts that already have an open/draft/paid renewal
 * invoice for the current renewalDueDate period.
 */
export async function runRenewalInvoiceJob(): Promise<{
  created: number;
  skipped: number;
  errors: number;
}> {
  const leadDays = env.renewalInvoiceLeadDays;
  const today = startOfDay(new Date());
  const windowEnd = endOfDay(
    new Date(today.getTime() + leadDays * 24 * 60 * 60 * 1000),
  );

  const contracts = await Contract.find({
    renewalDueDate: { $ne: null, $lte: windowEnd },
  }).limit(500);

  let created = 0;
  let skipped = 0;
  let errors = 0;

  for (const contract of contracts) {
    try {
      if (!contract.renewalDueDate) {
        skipped += 1;
        continue;
      }

      const existing = await Invoice.findOne({
        contractRef: contract._id,
        sourceType: "contract_renewal",
        status: { $in: ["open", "draft", "paid"] },
        "metadata.renewalDueDate": contract.renewalDueDate,
      });

      // Also treat any open renewal invoice without matching metadata as blocking
      const openAny = existing
        ? existing
        : await Invoice.findOne({
            contractRef: contract._id,
            sourceType: "contract_renewal",
            status: { $in: ["open", "draft"] },
          });

      if (openAny) {
        skipped += 1;
        continue;
      }

      // Skip if already paid for this due date
      const paidForDue = await Invoice.findOne({
        contractRef: contract._id,
        sourceType: "contract_renewal",
        status: "paid",
        "metadata.renewalDueDate": contract.renewalDueDate,
      });
      if (paidForDue) {
        skipped += 1;
        continue;
      }

      let cost = 0;
      let templateLabel: string | undefined;
      if (contract.templateId) {
        const template = await ContractTemplate.findById(contract.templateId)
          .select("cost label")
          .lean();
        cost = template?.cost ?? 0;
        templateLabel = template?.label;
      }

      const amountCents = dollarsToCents(cost);
      if (amountCents <= 0) {
        skipped += 1;
        continue;
      }

      const issuedAt = new Date();
      await Invoice.create({
        number: await nextInvoiceNumber(issuedAt),
        customerId: contract.customerId,
        customerRef: contract.customerRef,
        sourceType: "contract_renewal",
        contractRef: contract._id as Types.ObjectId,
        templateRef: contract.templateId ?? null,
        lineItems: [
          {
            description: `Contract renewal${templateLabel ? `: ${templateLabel}` : ""}`,
            amountCents,
          },
        ],
        amountCents,
        currency: "USD",
        status: "open",
        dueDate: contract.renewalDueDate,
        issuedAt,
        metadata: {
          durationMonths: contract.durationMonths,
          renewalDueDate: contract.renewalDueDate,
          autoGenerated: true,
          templateLabel,
        },
      });
      created += 1;
    } catch (err) {
      errors += 1;
      console.error(
        `[renewal-invoices] failed for contract ${contract._id}`,
        err,
      );
    }
  }

  return { created, skipped, errors };
}
